services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SchedulingBundle\Service\Factory\JobCsvFactory: ~
    SchedulingBundle\Service\Factory\JobAttachmentFactory: ~
    SchedulingBundle\Service\Factory\JobPdfFactory: ~
