services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SchedulingBundle\FileManager\JobAttachmentFileManager:
        $attachmentsDir: "%kernel.root_dir%/data/scheduling/attachments"
