## CustomAttribute (object)
+ name: `Personal Code`
+ attributeType: `client` (enum[string])
    + Members
        + `client`
        + `invoice`

## CustomAttributeReadOnly (object)
+ id: `2000` (number)
+ key: `personalCode` (string)
+ Include CustomAttribute
