## Error404 (object)
+ code: `404` (number) - Error code
+ message: `Object is not found.` - Error description message

## Error422 (object)
+ code: `422` (number) - Error code
+ message: `Validation failed.` - Error description message
+ errors
    + someField: `Some validation error description message.` (array[string]) - Array of validation errors 
