## InvoiceAttribute (object)
+ value: `lorem ipsum` (string)
+ customAttributeId: `1` (number)
    See [Retrieve Custom Attributes](#reference/custom-attributes/custom-attributes/get)

## InvoiceAttributeReadOnly (object)
+ id: `2000` (number)
+ invoiceId: `1000` (number)
+ name: `Personal Code` (string)
+ key: `personalCode` (string)
+ Include InvoiceAttribute
