## InvoiceTemplateReadOnly (object)
+ id: `1` (number)
+ name: `Default` (string)
+ createdDate: `2017-09-12T00:00:00+0000` - Date string in ISO 8601 format
+ isOfficial: `true` (boolean)
+ isValid: `true` (boolean)
