## JobComment (object)
+ jobId: `1000` (required, number)
    See [Retrieve Jobs](#reference/jobs/schedulingjobs/get)
+ userId: `1` (number)
    See [Retrieve Users](#reference/users/usersadmins/get)
+ createdDate: `2016-09-12T00:00:00+0000` (string) - Date string in ISO 8601 format. If not specified, current date will be used
+ message: `This is a comment for this job.` (required, string)

## JobCommentWritable (object)
+ Include JobComment

## JobCommentReadOnly (object)
+ id: `2000` (number)
+ Include JobComment
