## JobTask (object)
+ jobId: `1000` (required, number)
    See [Retrieve Jobs](#reference/jobs/schedulingjobs/get)
+ label: `This is a task label.` (required, string)
+ closed (boolean)
    + Default: `false`

## JobTaskWritable (object)
+ Include JobTask

## JobTaskReadOnly (object)
+ id: `2000` (number)
+ Include JobTask
