## Product (object)
+ name: `UTP cable` (required)
+ invoiceLabel: `UTP cable` - If not specified, name will be used
+ price: `10.0` (number, required)
+ unit: `m`
+ taxable (boolean)
    + Default: `false`

## ProductReadOnly (object)
+ id: `1` (number)
+ Include Product
