## ServiceSurcharge (object)
+ surchargeId: `1` (number, required)
    See [Retrieve Surcharges](#reference/surcharges/surcharges/get)
+ invoiceLabel: `Public IP` - If not specified, surcharge name will be used
+ price: `10.0` (number) - Price per period
+ taxable (boolean)
    + Default: `false`

## ServiceSurchargeReadOnly (object)
+ id: `1` (number)
+ serviceId: `1` (number) 
+ Include ServiceSurcharge
