## Site (object)
+ name: `HQ` (required)
+ address: `2580 Orchard Pkwy, San Jose, CA 95131, USA` (required)
+ gpsLat: `37.3832548351597` (required) - Latitude of site location
+ gpsLon: `-121.931131237113` (required) - Longitude of site location
+ contactInfo
+ notes

## SiteReadOnly (object)
+ id: `249` (number)
+ Include Site
