## Surcharge (object)
+ name: `Public IP` (required)
+ invoiceLabel: `Public IP` - If not specified, name will be used
+ price: `10.0` (number, required)
+ taxable (boolean)
    + Default: `false`

## SurchargeReadOnly (object)
+ id: `1` (number)
+ Include Surcharge
