## Tax (object)
+ name: `VAT 10%` (string, required)
+ agencyName (string)
+ rate: `10.0` (number, required) - Tax rate in percentage

## TaxReadOnly (object)
+ id: `1` (number)
+ Include Tax
+ selected (boolean) - Is selected to be assigned to every new client as default
    + Default: `false`
