## TicketCommentAttachment
+ filename: `foto.jpg` (required, string) - File name

## TicketCommentAttachmentWritable (object)
+ file: `` (required, string) - File encoded in base64.
+ Include TicketCommentAttachment

## TicketCommentAttachmentReadOnly (object)
+ id: `1` (number)
+ size: `6983` (number) - Size of file in bytes
+ mimeType: `image/png` - MIME Type of file
+ Include TicketCommentAttachment
