## TicketActivityJobAssignment (object)
+ assignedJobId: `35` (number)
    See [Retrieve Jobs](#reference/scheduling/jobs/get)
+ type: `add` (enum[string])
    + Members
        + `add`
        + `remove`
