FORMAT: 1A
HOST: https://ucrm-demo.ui.com/api/v1.0

# UCRM API

## Authentication

:[Authentication Description](authentication/description.apib)


# Group Clients

:[Client](resources/client.apib)


# Group Client Contacts

:[ClientContact](resources/client_contact.apib)


# Group Client Logs

:[ClientLogs](resources/client_logs.apib)


# Group Client Tags

:[ClientTags](resources/client_tags.apib)


# Group Custom Attributes

:[Custom Attribute](resources/custom_attribute.apib)


# Group Device Interfaces

:[Device Interface](resources/device_interface.apib)


# Group Devices

:[Device](resources/device.apib)


# Group Invoice Templates

:[Invoice Template](resources/invoice_template.apib)


# Group Invoices

:[Invoice](resources/invoice.apib)


# Group Job Attachments

:[Job Attachment](resources/job_attachment.apib)


# Group Job Comments

:[Job Comment](resources/job_comment.apib)


# Group Job Tasks

:[Job Task](resources/job_task.apib)


# Group Jobs

:[Job](resources/job.apib)


# Group Organizations

:[Organization](resources/organization.apib)


# Group Payment Plans

:[PaymentPlan](resources/payment_plan.apib)


# Group Payments

:[Payment](resources/payment.apib)


# Group Products

:[Product](resources/product.apib)


# Group Proforma Invoice Templates

:[Invoice Template](resources/proforma_invoice_template.apib)


# Group Quote Templates

:[Quote Template](resources/quote_template.apib)


# Group Quotes

:[Quote](resources/quote.apib)


# Group Refund

:[Payment](resources/refund.apib)


# Group Service Devices

:[Service Device](resources/service_device.apib)


# Group Service IPs

:[Service Ip](resources/service_ip.apib)


# Group Service Plans

:[Service Plan](resources/tariff.apib)


# Group Service Surcharges

:[Service Surcharge](resources/service_surcharge.apib)


# Group Services

:[Service](resources/service.apib)


# Group Sites

:[Site](resources/site.apib)


# Group Surcharges

:[Surcharge](resources/surcharge.apib)


# Group Taxes

:[Tax](resources/tax.apib)


# Group Ticket Activity

:[Ticket Activity](resources/ticket_activity.apib)


# Group Ticket Comment Attachments

:[Ticket](resources/ticket_comment_attachment.apib)


# Group Ticket Comments

:[Ticket](resources/ticket_comment.apib)


# Group Ticket Groups

:[Ticket](resources/ticket_group.apib)


# Group Tickets

:[Ticket](resources/ticket.apib)


# Group Users

:[User](resources/user.apib)


# Group Vendors

:[Vendor](resources/vendor.apib)


# Group Webhook Events

:[WebhookEvent](resources/webhook_event.apib)


# Group General

Resources related to general questions in the API.

:[Version](resources/version.apib)

:[Country](resources/country.apib)

:[Currency](resources/currency.apib)

:[State](resources/state.apib)


# Group Mobile

:[Dashboard](resources/mobile.apib)


# Data Structures

:[Errors](objects/error.apib)

:[Version](objects/version.apib)

:[Country](objects/country.apib)

:[Currency](objects/currency.apib)

:[State](objects/state.apib)

:[Client](objects/client.apib)

:[ClientLogs](objects/client_logs.apib)

:[ClientContact](objects/client_contact.apib)

:[ClientBankAccount](objects/client_bank_account.apib)

:[ClientAttribute](objects/client_attribute.apib)

:[ClientTag](objects/client_tag.apib)

:[Service](objects/service.apib)

:[Service Device](objects/service_device.apib)

:[Service Ip](objects/service_ip.apib)

:[Service Surcharge](objects/service_surcharge.apib)

:[Site](objects/site.apib)

:[Device](objects/device.apib)

:[DeviceInterface](objects/device_interface.apib)

:[Invoice](objects/invoice.apib)

:[Quote](objects/quote.apib)

:[Invoice Template](objects/invoice_template.apib)

:[Proforma Invoice Template](objects/proforma_invoice_template.apib)

:[Invoice Attribute](objects/invoice_attribute.apib)

:[Quote Template](objects/quote_template.apib)

:[Payment](objects/payment.apib)

:[Refund](objects/refund.apib)

:[PaymentPlan](objects/payment_plan.apib)

:[User](objects/user.apib)

:[Organization](objects/organization.apib)

:[Service Plan](objects/tariff.apib)

:[Surcharge](objects/surcharge.apib)

:[Tax](objects/tax.apib)

:[Product](objects/product.apib)

:[Vendor](objects/vendor.apib)

:[PaymentCover](objects/payment_cover.apib)

:[Job](objects/job.apib)

:[JobAttachment](objects/job_attachment.apib)

:[JobComment](objects/job_comment.apib)

:[JobTask](objects/job_task.apib)

:[CustomAttribute](objects/custom_attribute.apib)

:[Ticket](objects/ticket.apib)

:[TicketActivity](objects/ticket_activity.apib)

:[TicketActivityClientAssignment](objects/ticket_activity_client_assignment.apib)

:[TicketActivityJobAssignment](objects/ticket_activity_job_assignment.apib)

:[TicketActivityComment](objects/ticket_activity_comment.apib)

:[TicketActivityStatusChange](objects/ticket_activity_status_change.apib)

:[TicketActivityUserAssignment](objects/ticket_activity_user_assignment.apib)

:[TicketComment](objects/ticket_comment.apib)

:[TicketCommentAttachment](objects/ticket_comment_attachment.apib)

:[TicketGroup](objects/ticket_group.apib)

:[ContactType](objects/contact_type.apib)

:[WebhookEvent](objects/webhook_event.apib)
