## GET /currencies

Retrieve collection of **Currencies**.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (array[CurrencyReadOnly])

## GET /currencies/{id}

Retrieve **Currency**.

+ Parameters
    + id: `1` (number, required) - ID of a **Currency** to fetch.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (CurrencyReadOnly)

+ Response 404 (application/json)
    + Attributes (Error404)
