## GET /invoice-templates
Retrieve collection of **Invoice Templates**.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (array[InvoiceTemplateReadOnly])

+ Response 404 (application/json)
    + Attributes (Error404)

## GET /invoice-templates/{id}
Retrieve **Invoice Template**.

+ Parameters
    + id: `1` (number, required) - ID of an **Invoice Template** to fetch.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (InvoiceTemplateReadOnly)

+ Response 404 (application/json)
    + Attributes (Error404)
