# /payment-plans

## GET

Retrieve collection of **Payment Plans**.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (array[PaymentPlanReadOnly])

## POST

Create **Payment Plan**.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

    + Attributes (PaymentPlan)

+ Response 201 (application/json)
    + Headers

            Location: /payment-plans/2
    + Attributes (PaymentPlanReadOnly)

+ Response 422 (application/json)
    + Attributes (Error422)

# /payment-plans/{id}

## GET

Retrieve **Payment Plan**.

+ Parameters
    + id: `1` (number, required) - ID of a **Payment Plan** to fetch.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (PaymentPlanReadOnly)

+ Response 404 (application/json)
    + Attributes (Error404)

# /payment-plans/{id}/cancel
## PATCH

Cancel **Payment Plan**.

+ Parameters
    + id: `1` (number, required) - ID of a **Payment Plan** to cancel.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (PaymentPlanReadOnly)

+ Response 404 (application/json)
    + Attributes (Error404)

+ Response 422 (application/json)
    + Attributes (Error422)
