## GET /ticketing/tickets/comments{?ticketId,userId,createdDateFrom,createdDateTo}

Retrieve collection of **Ticket Comments**.

+ Parameters
    + ticketId: `1` (number, optional) - ID of a **Ticket** to filter by.

    + userId: `1` (number, optional) - ID of a **User** to filter by.

    + createdDateFrom: `2016-01-01` (string, optional) -  Limit collection from date (including).
    Use `YYYY-MM-DD` format.

    + createdDateTo: `2016-12-31` (string, optional) -  Limit collection to date (including).
    Use `YYYY-MM-DD` format.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (array[TicketCommentReadOnly])

+ Response 404 (application/json)
    + Attributes (Error404)

## POST /ticketing/tickets/comments

Create **Ticket Comment**.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

    + Attributes (TicketCommentWritable)

+ Response 201 (application/json)
    + Headers

            Location: /ticketing/tickets/comments/1001
    + Attributes (TicketCommentReadOnly)

+ Response 422 (application/json)
    + Attributes (Error422)

## GET /ticketing/tickets/comments/{id}

Retrieve **Ticket Comment**.

+ Parameters
    + id: `1000` (number, required) - ID of a **Ticket Comment** to fetch.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (TicketCommentReadOnly)

+ Response 404 (application/json)
    + Attributes (Error404)
