## GET /ticketing/tickets/comments/attachments/{id}/file

Retrieve **Ticket Comment Attachment** file resource.

+ Parameters
    + id: `1000` (number, required) - ID of a **Ticket Comment** to fetch.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (*/*)


+ Response 404 (application/json)
    + Attributes (Error404)
