## GET /version

Retrieve currently installed UCRM version.

+ Request (application/json)
    :[Authentication Headers](../authentication/headers.apib)

+ Response 200 (application/json)
    + Attributes (Version)
